baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Project Showcase'
theme = 'newsroom'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"